<?php
// RaCore CMS Configuration
// Generated by RaCore SiteBuilder Module

// Database configuration
define('DB_PATH', __DIR__ . '/../Databases/cms_database.sqlite');

// Site settings
define('SITE_NAME', 'RaCore CMS');
define('SITE_URL', 'http://localhost');

// Security settings
define('SESSION_LIFETIME', 3600);

session_start();
date_default_timezone_set('UTC');
error_reporting(E_ALL);
ini_set('display_errors', '1');
?>