using Microsoft.Data.Sqlite;

namespace RaCore.Modules.Extensions.SiteBuilder;

/// <summary>
/// Generates CMS homepage with SQLite database.
/// </summary>
public class CmsGenerator
{
    private readonly SiteBuilderModule _module;
    private readonly string _cmsRootPath;

    public CmsGenerator(SiteBuilderModule module, string cmsRootPath)
    {
        _module = module;
        _cmsRootPath = cmsRootPath;
    }

    public string GenerateHomepage(string phpPath)
    {
        try
        {
            _module.Log("Starting CMS homepage generation...");

            var version = GetPhpVersion(phpPath);
            _module.Log($"PHP detected: {version}");

            // Create CMS directory
            if (!Directory.Exists(_cmsRootPath))
            {
                Directory.CreateDirectory(_cmsRootPath);
                _module.Log($"Created CMS directory: {_cmsRootPath}");
            }

            // Initialize SQLite database - use GetCurrentDirectory() for server root
            var dbPath = Path.Combine(Directory.GetCurrentDirectory(), "Databases", "cms_database.sqlite");
            var databasesFolder = Path.GetDirectoryName(dbPath);
            if (databasesFolder != null && !Directory.Exists(databasesFolder))
            {
                Directory.CreateDirectory(databasesFolder);
            }
            
            InitializeSQLiteDatabase(dbPath);

            // Generate PHP files
            GenerateConfigFile(dbPath);
            GenerateDatabaseFile();
            GenerateIndexFile();
            GenerateAdminFile();
            GenerateStylesFile();

            return $"✅ CMS homepage generated successfully at: {_cmsRootPath}";
        }
        catch (Exception ex)
        {
            _module.Log($"CMS generation failed: {ex.Message}", "ERROR");
            return $"❌ Error generating CMS: {ex.Message}";
        }
    }

    private string GetPhpVersion(string phpPath)
    {
        // This will be extracted from original code
        return "PHP 8+";
    }

    private void InitializeSQLiteDatabase(string dbPath)
    {
        using var connection = new SqliteConnection($"Data Source={dbPath}");
        connection.Open();

        var command = connection.CreateCommand();
        command.CommandText = @"
            CREATE TABLE IF NOT EXISTS pages (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                title TEXT NOT NULL,
                content TEXT,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
            );

            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                username TEXT UNIQUE NOT NULL,
                password TEXT NOT NULL,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP
            );

            CREATE TABLE IF NOT EXISTS settings (
                key TEXT PRIMARY KEY,
                value TEXT
            );

            INSERT OR IGNORE INTO users (username, password) VALUES ('admin', 'admin123');
            INSERT OR IGNORE INTO settings (key, value) VALUES ('site_name', 'RaCore CMS');
            INSERT OR IGNORE INTO pages (title, content) VALUES ('Welcome', '<h1>Welcome to RaCore CMS</h1><p>This is your homepage.</p>');
        ";
        
        command.ExecuteNonQuery();
        _module.Log($"SQLite database initialized: {dbPath}");
    }

    private void GenerateConfigFile(string dbPath)
    {
        var relativePath = GetRelativeDatabasePath(dbPath);
        var content = $@"<?php
// RaCore CMS Configuration
// Generated by RaCore SiteBuilder Module

// Database configuration
define('DB_PATH', __DIR__ . '/{relativePath}');

// Site settings
define('SITE_NAME', 'RaCore CMS');
define('SITE_URL', 'http://localhost');

// Security settings
define('SESSION_LIFETIME', 3600);

session_start();
date_default_timezone_set('UTC');
error_reporting(E_ALL);
ini_set('display_errors', '1');
?>";

        File.WriteAllText(Path.Combine(_cmsRootPath, "config.php"), content);
        _module.Log("Generated config.php");
    }

    private void GenerateDatabaseFile()
    {
        var content = @"<?php
// Database layer for RaCore CMS

class Database {
    private $db;
    
    public function __construct() {
        $this->db = new PDO('sqlite:' . DB_PATH);
        $this->db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    }
    
    public function query($sql, $params = []) {
        $stmt = $this->db->prepare($sql);
        $stmt->execute($params);
        return $stmt->fetchAll(PDO::FETCH_ASSOC);
    }
    
    public function execute($sql, $params = []) {
        $stmt = $this->db->prepare($sql);
        return $stmt->execute($params);
    }
}
?>";

        File.WriteAllText(Path.Combine(_cmsRootPath, "db.php"), content);
        _module.Log("Generated db.php");
    }

    private void GenerateIndexFile()
    {
        var content = @"<?php
require_once 'config.php';
require_once 'db.php';

$db = new Database();
$pages = $db->query('SELECT * FROM pages LIMIT 1');
$page = $pages[0] ?? ['title' => 'Welcome', 'content' => 'No content'];
?>
<!DOCTYPE html>
<html>
<head>
    <title><?php echo htmlspecialchars($page['title']); ?> - <?php echo SITE_NAME; ?></title>
    <link rel='stylesheet' href='styles.css'>
</head>
<body>
    <div class='container'>
        <nav class='main-nav'>
            <div class='nav-brand'><?php echo SITE_NAME; ?></div>
            <div class='nav-links'>
                <a href='index.php'>Home</a>
                <a href='admin.php'>Admin Panel</a>
                <a href='/control-panel.html' target='_blank'>RaCore Control Panel</a>
            </div>
        </nav>
        <div class='content'>
            <?php echo $page['content']; ?>
        </div>
        <footer class='site-footer'>
            <p>Powered by RaCore | <a href='/control-panel.html'>Manage Your Site</a></p>
        </footer>
    </div>
</body>
</html>";

        File.WriteAllText(Path.Combine(_cmsRootPath, "index.php"), content);
        _module.Log("Generated index.php with RaCore Control Panel integration");
    }

    private void GenerateAdminFile()
    {
        var content = @"<?php
require_once 'config.php';
require_once 'db.php';

session_start();

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $username = $_POST['username'] ?? '';
    $password = $_POST['password'] ?? '';
    
    $db = new Database();
    $users = $db->query('SELECT * FROM users WHERE username = ?', [$username]);
    
    if (!empty($users) && $users[0]['password'] === $password) {
        $_SESSION['logged_in'] = true;
        $_SESSION['username'] = $username;
    }
}

if (!isset($_SESSION['logged_in']) || !$_SESSION['logged_in']) {
    ?>
    <!DOCTYPE html>
    <html>
    <head>
        <title>Admin Login - <?php echo SITE_NAME; ?></title>
        <link rel='stylesheet' href='styles.css'>
        <style>
            .login-container {
                min-height: 100vh;
                display: flex;
                align-items: center;
                justify-content: center;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            }
            .login-box {
                background: white;
                padding: 40px;
                border-radius: 15px;
                box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);
                max-width: 400px;
                width: 100%;
            }
            .login-box input {
                width: 100%;
                padding: 12px;
                margin: 10px 0;
                border: 2px solid #e0e0e0;
                border-radius: 8px;
            }
            .login-box button {
                width: 100%;
                padding: 12px;
                background: #667eea;
                color: white;
                border: none;
                border-radius: 8px;
                cursor: pointer;
                font-size: 16px;
                font-weight: bold;
            }
        </style>
    </head>
    <body>
        <div class='login-container'>
            <div class='login-box'>
                <h2>Admin Login</h2>
                <form method='post'>
                    <input name='username' placeholder='Username' required>
                    <input type='password' name='password' placeholder='Password' required>
                    <button>Login</button>
                </form>
                <p style='margin-top: 20px; text-align: center;'>
                    <a href='index.php'>Back to Homepage</a>
                </p>
            </div>
        </div>
    </body>
    </html>
    <?php
    exit;
}
?>
<!DOCTYPE html>
<html>
<head>
    <title>Admin Panel - <?php echo SITE_NAME; ?></title>
    <link rel='stylesheet' href='styles.css'>
</head>
<body>
    <div class='container'>
        <nav class='main-nav'>
            <div class='nav-brand'>Admin Panel - <?php echo SITE_NAME; ?></div>
            <div class='nav-links'>
                <a href='index.php'>Home</a>
                <a href='admin.php'>Admin</a>
                <a href='/control-panel.html' target='_blank'>RaCore Control Panel</a>
                <a href='?logout=1'>Logout</a>
            </div>
        </nav>
        <div class='content'>
            <h1>Welcome, <?php echo htmlspecialchars($_SESSION['username']); ?>!</h1>
            
            <div style='margin: 30px 0; padding: 20px; background: #f8f9fa; border-radius: 10px;'>
                <h2 style='color: #667eea; margin-bottom: 15px;'>Quick Actions</h2>
                <ul style='list-style: none; padding: 0;'>
                    <li style='margin: 10px 0;'>
                        <a href='/control-panel.html' target='_blank' style='display: inline-block; padding: 10px 20px; background: #667eea; color: white; border-radius: 5px; text-decoration: none;'>
                            🎛️ Open RaCore Control Panel
                        </a>
                    </li>
                    <li style='margin: 10px 0; color: #666;'>
                        📝 Manage Pages (Coming Soon)
                    </li>
                    <li style='margin: 10px 0; color: #666;'>
                        👥 Manage Users (Coming Soon)
                    </li>
                    <li style='margin: 10px 0; color: #666;'>
                        ⚙️ Site Settings (Coming Soon)
                    </li>
                </ul>
            </div>
            
            <div style='margin: 30px 0; padding: 20px; background: #e8f4f8; border-radius: 10px; border-left: 4px solid #667eea;'>
                <h3 style='color: #667eea; margin-bottom: 10px;'>💡 Pro Tip</h3>
                <p>Use the <strong>RaCore Control Panel</strong> for advanced management including:</p>
                <ul style='margin-top: 10px;'>
                    <li>User & Role Management</li>
                    <li>License Management</li>
                    <li>RaCoin Wallet Management</li>
                    <li>Game Server Configuration</li>
                    <li>Forum Moderation</li>
                </ul>
            </div>
        </div>
        <footer class='site-footer'>
            <p>Powered by RaCore | <a href='/control-panel.html'>Advanced Management</a></p>
        </footer>
    </div>
</body>
</html>";

        File.WriteAllText(Path.Combine(_cmsRootPath, "admin.php"), content);
        _module.Log("Generated admin.php with RaCore Control Panel integration");
    }

    private void GenerateStylesFile()
    {
        var content = @"body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 0;
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: #333;
    min-height: 100vh;
}

.container {
    max-width: 1200px;
    margin: 0 auto;
    background: white;
    min-height: 100vh;
    box-shadow: 0 0 60px rgba(0,0,0,0.3);
}

.main-nav {
    background: #667eea;
    padding: 15px 30px;
    display: flex;
    justify-content: space-between;
    align-items: center;
    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
}

.nav-brand {
    color: white;
    font-size: 24px;
    font-weight: bold;
}

.nav-links {
    display: flex;
    gap: 20px;
}

.nav-links a {
    color: white;
    text-decoration: none;
    padding: 8px 16px;
    border-radius: 5px;
    transition: background 0.3s;
}

.nav-links a:hover {
    background: rgba(255,255,255,0.2);
}

.content {
    padding: 40px 30px;
    min-height: 400px;
}

h1 {
    color: #667eea;
    border-bottom: 3px solid #764ba2;
    padding-bottom: 10px;
    margin-bottom: 20px;
}

a {
    color: #667eea;
    text-decoration: none;
    font-weight: bold;
}

a:hover {
    color: #764ba2;
}

.site-footer {
    background: #f5f5f5;
    padding: 20px 30px;
    text-align: center;
    color: #666;
    border-top: 1px solid #ddd;
}

.site-footer a {
    color: #667eea;
    margin-left: 10px;
}";

        File.WriteAllText(Path.Combine(_cmsRootPath, "styles.css"), content);
        _module.Log("Generated styles.css with integrated navigation");
    }

    private string GetRelativeDatabasePath(string dbPath)
    {
        var cmsUri = new Uri(_cmsRootPath + Path.DirectorySeparatorChar);
        var dbUri = new Uri(dbPath);
        var relativeUri = cmsUri.MakeRelativeUri(dbUri);
        return Uri.UnescapeDataString(relativeUri.ToString()).Replace('/', Path.DirectorySeparatorChar);
    }
}
