using Microsoft.Data.Sqlite;

namespace RaCore.Modules.Extensions.SiteBuilder;

/// <summary>
/// Generates CMS homepage with SQLite database.
/// </summary>
public class CmsGenerator
{
    private readonly SiteBuilderModule _module;
    private readonly string _cmsRootPath;

    public CmsGenerator(SiteBuilderModule module, string cmsRootPath)
    {
        _module = module;
        _cmsRootPath = cmsRootPath;
    }

    public string GenerateHomepage(string phpPath)
    {
        try
        {
            _module.Log("Starting CMS homepage generation...");

            var version = GetPhpVersion(phpPath);
            _module.Log($"PHP detected: {version}");

            // Create CMS directory
            if (!Directory.Exists(_cmsRootPath))
            {
                Directory.CreateDirectory(_cmsRootPath);
                _module.Log($"Created CMS directory: {_cmsRootPath}");
            }

            // Initialize SQLite database
            var dbPath = Path.Combine(AppContext.BaseDirectory, "Databases", "cms_database.sqlite");
            var databasesFolder = Path.GetDirectoryName(dbPath);
            if (databasesFolder != null && !Directory.Exists(databasesFolder))
            {
                Directory.CreateDirectory(databasesFolder);
            }
            
            InitializeSQLiteDatabase(dbPath);

            // Generate PHP files
            GenerateConfigFile(dbPath);
            GenerateDatabaseFile();
            GenerateIndexFile();
            GenerateAdminFile();
            GenerateStylesFile();

            return $"✅ CMS homepage generated successfully at: {_cmsRootPath}";
        }
        catch (Exception ex)
        {
            _module.Log($"CMS generation failed: {ex.Message}", "ERROR");
            return $"❌ Error generating CMS: {ex.Message}";
        }
    }

    private string GetPhpVersion(string phpPath)
    {
        // This will be extracted from original code
        return "PHP 8+";
    }

    private void InitializeSQLiteDatabase(string dbPath)
    {
        using var connection = new SqliteConnection($"Data Source={dbPath}");
        connection.Open();

        var command = connection.CreateCommand();
        command.CommandText = @"
            CREATE TABLE IF NOT EXISTS pages (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                title TEXT NOT NULL,
                content TEXT,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
            );

            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                username TEXT UNIQUE NOT NULL,
                password TEXT NOT NULL,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP
            );

            CREATE TABLE IF NOT EXISTS settings (
                key TEXT PRIMARY KEY,
                value TEXT
            );

            INSERT OR IGNORE INTO users (username, password) VALUES ('admin', 'admin123');
            INSERT OR IGNORE INTO settings (key, value) VALUES ('site_name', 'RaCore CMS');
            INSERT OR IGNORE INTO pages (title, content) VALUES ('Welcome', '<h1>Welcome to RaCore CMS</h1><p>This is your homepage.</p>');
        ";
        
        command.ExecuteNonQuery();
        _module.Log($"SQLite database initialized: {dbPath}");
    }

    private void GenerateConfigFile(string dbPath)
    {
        var relativePath = GetRelativeDatabasePath(dbPath);
        var content = $@"<?php
// RaCore CMS Configuration
// Generated by RaCore SiteBuilder Module

// Database configuration
define('DB_PATH', __DIR__ . '/{relativePath}');

// Site settings
define('SITE_NAME', 'RaCore CMS');
define('SITE_URL', 'http://localhost');

// Security settings
define('SESSION_LIFETIME', 3600);

session_start();
date_default_timezone_set('UTC');
error_reporting(E_ALL);
ini_set('display_errors', '1');
?>";

        File.WriteAllText(Path.Combine(_cmsRootPath, "config.php"), content);
        _module.Log("Generated config.php");
    }

    private void GenerateDatabaseFile()
    {
        var content = @"<?php
// Database layer for RaCore CMS

class Database {
    private $db;
    
    public function __construct() {
        $this->db = new PDO('sqlite:' . DB_PATH);
        $this->db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    }
    
    public function query($sql, $params = []) {
        $stmt = $this->db->prepare($sql);
        $stmt->execute($params);
        return $stmt->fetchAll(PDO::FETCH_ASSOC);
    }
    
    public function execute($sql, $params = []) {
        $stmt = $this->db->prepare($sql);
        return $stmt->execute($params);
    }
}
?>";

        File.WriteAllText(Path.Combine(_cmsRootPath, "db.php"), content);
        _module.Log("Generated db.php");
    }

    private void GenerateIndexFile()
    {
        var content = @"<?php
require_once 'config.php';
require_once 'db.php';

$db = new Database();
$pages = $db->query('SELECT * FROM pages LIMIT 1');
$page = $pages[0] ?? ['title' => 'Welcome', 'content' => 'No content'];
?>
<!DOCTYPE html>
<html>
<head>
    <title><?php echo htmlspecialchars($page['title']); ?> - <?php echo SITE_NAME; ?></title>
    <link rel='stylesheet' href='styles.css'>
</head>
<body>
    <div class='container'>
        <h1><?php echo SITE_NAME; ?></h1>
        <div class='content'>
            <?php echo $page['content']; ?>
        </div>
        <a href='admin.php'>Admin Panel</a>
    </div>
</body>
</html>";

        File.WriteAllText(Path.Combine(_cmsRootPath, "index.php"), content);
        _module.Log("Generated index.php");
    }

    private void GenerateAdminFile()
    {
        var content = @"<?php
require_once 'config.php';
require_once 'db.php';

session_start();

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $username = $_POST['username'] ?? '';
    $password = $_POST['password'] ?? '';
    
    $db = new Database();
    $users = $db->query('SELECT * FROM users WHERE username = ?', [$username]);
    
    if (!empty($users) && $users[0]['password'] === $password) {
        $_SESSION['logged_in'] = true;
        $_SESSION['username'] = $username;
    }
}

if (!isset($_SESSION['logged_in']) || !$_SESSION['logged_in']) {
    echo '<form method='post'><input name='username' placeholder='Username'><input type='password' name='password' placeholder='Password'><button>Login</button></form>';
    exit;
}
?>
<!DOCTYPE html>
<html>
<head>
    <title>Admin Panel - <?php echo SITE_NAME; ?></title>
    <link rel='stylesheet' href='styles.css'>
</head>
<body>
    <div class='container'>
        <h1>Admin Panel</h1>
        <p>Logged in as: <?php echo htmlspecialchars($_SESSION['username']); ?></p>
        <a href='index.php'>Back to Homepage</a>
    </div>
</body>
</html>";

        File.WriteAllText(Path.Combine(_cmsRootPath, "admin.php"), content);
        _module.Log("Generated admin.php");
    }

    private void GenerateStylesFile()
    {
        var content = @"body {
    font-family: Arial, sans-serif;
    margin: 0;
    padding: 20px;
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: #333;
}

.container {
    max-width: 800px;
    margin: 0 auto;
    background: white;
    padding: 30px;
    border-radius: 10px;
    box-shadow: 0 10px 40px rgba(0,0,0,0.2);
}

h1 {
    color: #667eea;
    border-bottom: 3px solid #764ba2;
    padding-bottom: 10px;
}

a {
    color: #667eea;
    text-decoration: none;
    font-weight: bold;
}

a:hover {
    color: #764ba2;
}";

        File.WriteAllText(Path.Combine(_cmsRootPath, "styles.css"), content);
        _module.Log("Generated styles.css");
    }

    private string GetRelativeDatabasePath(string dbPath)
    {
        var cmsUri = new Uri(_cmsRootPath + Path.DirectorySeparatorChar);
        var dbUri = new Uri(dbPath);
        var relativeUri = cmsUri.MakeRelativeUri(dbUri);
        return Uri.UnescapeDataString(relativeUri.ToString()).Replace('/', Path.DirectorySeparatorChar);
    }
}
