namespace RaCore.Modules.Extensions.SiteBuilder;

/// <summary>
/// Generates wwwroot directory and control panel files for RaCore server.
/// </summary>
public class WwwrootGenerator
{
    private readonly SiteBuilderModule _module;
    private readonly string _wwwrootPath;

    public WwwrootGenerator(SiteBuilderModule module, string wwwrootPath)
    {
        _module = module;
        _wwwrootPath = wwwrootPath;
    }

    public string GenerateWwwroot()
    {
        try
        {
            _module.Log("Initializing Window of Ra (SiteBuilder)...");
            
            // Create wwwroot directory (for config files only, no static HTML)
            Directory.CreateDirectory(_wwwrootPath);
            
            // Create config subdirectory for server configuration files
            var configPath = Path.Combine(_wwwrootPath, "config");
            Directory.CreateDirectory(configPath);
            
            // NO HTML generation - all UI is served dynamically through internal routing
            // The Window of Ra (SiteBuilder) serves everything dynamically via RaOS
            
            // Generate server configuration files (optional for Linux environments)
            // On Windows 11, Kestrel is the only supported webserver
            if (!OperatingSystem.IsWindows())
            {
                GenerateNginxConfig(configPath);
                GenerateApacheConfig(configPath);
                GeneratePhpIni(configPath);
            }
            else
            {
                _module.Log("Skipping Apache/Nginx config generation on Windows (Kestrel is used)");
            }
            
            _module.Log($"✅ Window of Ra (SiteBuilder) initialized at: {_wwwrootPath}");
            
            var configFiles = OperatingSystem.IsWindows() 
                ? "  - No external configuration files needed (Kestrel webserver)" 
                : @"  - config/nginx.conf
  - config/apache.conf
  - config/php.ini";
            
            return $@"✅ Window of Ra (SiteBuilder) initialized successfully!

📁 Location: {_wwwrootPath}

🔒 SECURITY: All UI features are served dynamically through internal RaOS routing
   - No static HTML files generated
   - No external file access
   - All features accessed via Window of Ra (SiteBuilder module)

Available UI routes (dynamic, internal):
  - /login - Login interface
  - /control-panel - Main control panel
  - /admin - Administrative dashboard
  - /gameengine-dashboard - Game engine management
  - /clientbuilder-dashboard - Client builder interface

Configuration files:
{configFiles}

Note: {(OperatingSystem.IsWindows() ? "On Windows, RaCore uses Kestrel webserver (no external webserver needed)" : "Server configuration files generated for Linux environments")}";
        }
        catch (Exception ex)
        {
            _module.Log($"Window of Ra initialization failed: {ex.Message}", "ERROR");
            return $"❌ Error: {ex.Message}";
        }
    }

    private void GenerateNginxConfig(string configPath)
    {
        var cmsPath = _wwwrootPath;
        var content = $@"# Nginx Configuration for RaCore CMS Suite
# Generated by RaCore WwwrootGenerator
# Place this file in your Nginx sites-available directory

server {{
    listen 80;
    server_name localhost;
    root ""{cmsPath}"";
    index index.php index.html index.htm;
    
    # Enable gzip compression
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types text/plain text/css text/xml text/javascript application/x-javascript application/xml+rss application/json;
    
    location / {{
        try_files $uri $uri/ /index.php?$query_string;
    }}
    
    # PHP processing
    location ~ \.php$ {{
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass 127.0.0.1:9000;  # For PHP-FPM
        # fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;  # Alternative socket-based
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        
        # PHP settings
        fastcgi_buffer_size 128k;
        fastcgi_buffers 256 16k;
        fastcgi_busy_buffers_size 256k;
        fastcgi_temp_file_write_size 256k;
        fastcgi_read_timeout 240;
    }}
    
    # Control Panel
    location /control {{
        try_files $uri $uri/ /control/index.php?$query_string;
    }}
    
    # Static files caching
    location ~* \.(jpg|jpeg|png|gif|ico|css|js|svg|woff|woff2|ttf|eot)$ {{
        expires 1y;
        add_header Cache-Control ""public, immutable"";
        access_log off;
    }}
    
    # Deny access to sensitive files
    location ~ /\.ht {{
        deny all;
    }}
    
    location ~ /\.git {{
        deny all;
    }}
    
    location ~ /(config|includes|vendor)/ {{
        deny all;
    }}
    
    # Logging
    access_log /var/log/nginx/racore_access.log;
    error_log /var/log/nginx/racore_error.log;
}}
";
        
        File.WriteAllText(Path.Combine(configPath, "nginx.conf"), content);
        _module.Log("Generated config/nginx.conf");
    }
    
    private void GenerateApacheConfig(string configPath)
    {
        var cmsPath = _wwwrootPath;
        var content = $@"# Apache Configuration for RaCore CMS Suite
# Generated by RaCore WwwrootGenerator
# Place this file in your Apache sites-available directory
# Enable with: a2ensite racore.conf && systemctl reload apache2

<VirtualHost *:80>
    ServerName localhost
    ServerAdmin admin@localhost
    DocumentRoot ""{cmsPath}""
    
    <Directory ""{cmsPath}"">
        Options -Indexes +FollowSymLinks +MultiViews
        AllowOverride All
        Require all granted
        
        # Enable mod_rewrite for pretty URLs
        <IfModule mod_rewrite.c>
            RewriteEngine On
            RewriteBase /
            
            # Redirect to index.php if file/directory doesn't exist
            RewriteCond %{{REQUEST_FILENAME}} !-f
            RewriteCond %{{REQUEST_FILENAME}} !-d
            RewriteRule ^(.*)$ index.php?$1 [L,QSA]
        </IfModule>
    </Directory>
    
    # PHP Settings
    <IfModule mod_php8.c>
        php_value upload_max_filesize 50M
        php_value post_max_size 50M
        php_value memory_limit 256M
        php_value max_execution_time 300
        php_value max_input_time 300
    </IfModule>
    
    # Enable PHP-FPM if using it
    <FilesMatch \.php$>
        SetHandler ""proxy:unix:/var/run/php/php8.1-fpm.sock|fcgi://localhost/""
    </FilesMatch>
    
    # Security Headers
    <IfModule mod_headers.c>
        Header set X-Content-Type-Options ""nosniff""
        Header set X-Frame-Options ""SAMEORIGIN""
        Header set X-XSS-Protection ""1; mode=block""
        Header set Referrer-Policy ""no-referrer-when-downgrade""
    </IfModule>
    
    # Enable compression
    <IfModule mod_deflate.c>
        AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css text/javascript application/javascript application/json
    </IfModule>
    
    # Static file caching
    <IfModule mod_expires.c>
        ExpiresActive On
        ExpiresByType image/jpeg ""access plus 1 year""
        ExpiresByType image/png ""access plus 1 year""
        ExpiresByType image/gif ""access plus 1 year""
        ExpiresByType image/svg+xml ""access plus 1 year""
        ExpiresByType text/css ""access plus 1 year""
        ExpiresByType text/javascript ""access plus 1 year""
        ExpiresByType application/javascript ""access plus 1 year""
        ExpiresByType font/woff ""access plus 1 year""
        ExpiresByType font/woff2 ""access plus 1 year""
    </IfModule>
    
    # Deny access to sensitive files and directories
    <DirectoryMatch ""/(\.git|\.svn|config|includes|vendor)"">
        Require all denied
    </DirectoryMatch>
    
    <FilesMatch ""(\.htaccess|\.htpasswd|\.env|\.git.*|composer\.(json|lock))"">
        Require all denied
    </FilesMatch>
    
    # Logging
    ErrorLog ${{APACHE_LOG_DIR}}/racore_error.log
    CustomLog ${{APACHE_LOG_DIR}}/racore_access.log combined
</VirtualHost>

# SSL Configuration (uncomment and configure for HTTPS)
# <VirtualHost *:443>
#     ServerName localhost
#     ServerAdmin admin@localhost
#     DocumentRoot ""{cmsPath}""
#     
#     SSLEngine on
#     SSLCertificateFile /path/to/cert.pem
#     SSLCertificateKeyFile /path/to/key.pem
#     
#     # Include same directives as above
# </VirtualHost>
";
        
        File.WriteAllText(Path.Combine(configPath, "apache.conf"), content);
        _module.Log("Generated config/apache.conf");
    }
    
    private void GeneratePhpIni(string configPath)
    {
        var content = @"; PHP Configuration for RaCore CMS Suite
; Generated by RaCore WwwrootGenerator
; Place this file in your PHP configuration directory or use with -c flag

[PHP]
;;;;;;;;;;;;;;;;;;;;
; Language Options ;
;;;;;;;;;;;;;;;;;;;;

engine = On
short_open_tag = Off
precision = 14
output_buffering = 4096
zlib.output_compression = Off
implicit_flush = Off
unserialize_callback_func =
serialize_precision = -1
disable_functions =
disable_classes =
zend.enable_gc = On
zend.exception_ignore_args = On
zend.exception_string_param_max_len = 0

;;;;;;;;;;;;;;;;;
; Miscellaneous ;
;;;;;;;;;;;;;;;;;

expose_php = Off

;;;;;;;;;;;;;;;;;;;
; Resource Limits ;
;;;;;;;;;;;;;;;;;;;

max_execution_time = 300
max_input_time = 300
max_input_vars = 5000
memory_limit = 256M

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Error handling and logging ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
display_errors = On
display_startup_errors = On
log_errors = On
log_errors_max_len = 1024
ignore_repeated_errors = Off
ignore_repeated_source = Off
report_memleaks = On
error_log = /var/log/php_errors.log

;;;;;;;;;;;;;;;;;
; Data Handling ;
;;;;;;;;;;;;;;;;;

variables_order = ""GPCS""
request_order = ""GP""
register_argc_argv = Off
auto_globals_jit = On
post_max_size = 50M
auto_prepend_file =
auto_append_file =
default_mimetype = ""text/html""
default_charset = ""UTF-8""

;;;;;;;;;;;;;;;;;;;;;;;;;
; Paths and Directories ;
;;;;;;;;;;;;;;;;;;;;;;;;;

include_path = "".:/usr/share/php""
doc_root =
user_dir =
extension_dir = ""/usr/lib/php/20210902""
cgi.force_redirect = 1
cgi.fix_pathinfo = 0

;;;;;;;;;;;;;;;;
; File Uploads ;
;;;;;;;;;;;;;;;;

file_uploads = On
upload_tmp_dir = /tmp
upload_max_filesize = 50M
max_file_uploads = 20

;;;;;;;;;;;;;;;;;;
; Fopen wrappers ;
;;;;;;;;;;;;;;;;;;

allow_url_fopen = On
allow_url_include = Off
default_socket_timeout = 60

;;;;;;;;;;;;;;;;;;;
; Module Settings ;
;;;;;;;;;;;;;;;;;;;

[CLI Server]
cli_server.color = On

[Date]
date.timezone = UTC

[filter]
filter.default = unsafe_raw
filter.default_flags =

[iconv]
iconv.input_encoding = UTF-8
iconv.internal_encoding = UTF-8
iconv.output_encoding = UTF-8

[imap]

[intl]

[sqlite3]
sqlite3.extension_dir =
sqlite3.defensive = 1

[Pcre]
pcre.backtrack_limit = 100000
pcre.recursion_limit = 100000
pcre.jit = 1

[Pdo]

[Pdo_mysql]
pdo_mysql.default_socket =

[Phar]

[mail function]
SMTP = localhost
smtp_port = 25
mail.add_x_header = Off

[ODBC]
odbc.allow_persistent = On
odbc.check_persistent = On
odbc.max_persistent = -1
odbc.max_links = -1
odbc.defaultlrl = 4096
odbc.defaultbinmode = 1

[MySQLi]
mysqli.max_persistent = -1
mysqli.allow_persistent = On
mysqli.max_links = -1
mysqli.default_port = 3306
mysqli.default_socket =
mysqli.default_host =
mysqli.default_user =
mysqli.default_pw =
mysqli.reconnect = Off

[mysqlnd]
mysqlnd.collect_statistics = On
mysqlnd.collect_memory_statistics = Off

[PostgreSQL]
pgsql.allow_persistent = On
pgsql.auto_reset_persistent = Off
pgsql.max_persistent = -1
pgsql.max_links = -1
pgsql.ignore_notice = 0
pgsql.log_notice = 0

[bcmath]
bcmath.scale = 0

[Session]
session.save_handler = files
session.save_path = ""/tmp""
session.use_strict_mode = 1
session.use_cookies = 1
session.use_only_cookies = 1
session.name = RACORE_SESSID
session.auto_start = 0
session.cookie_lifetime = 0
session.cookie_path = /
session.cookie_domain =
session.cookie_httponly = 1
session.cookie_samesite = Lax
session.serialize_handler = php
session.gc_probability = 1
session.gc_divisor = 1000
session.gc_maxlifetime = 1440
session.referer_check =
session.cache_limiter = nocache
session.cache_expire = 180
session.use_trans_sid = 0
session.sid_length = 26
session.trans_sid_tags = ""a=href,area=href,frame=src,form=""
session.sid_bits_per_character = 5

[Assertion]
zend.assertions = 1

[mbstring]
mbstring.language = English
mbstring.internal_encoding = UTF-8
mbstring.http_output = UTF-8
mbstring.encoding_translation = Off

[gd]

[exif]

[Tidy]
tidy.clean_output = Off

[soap]
soap.wsdl_cache_enabled = 1
soap.wsdl_cache_dir = ""/tmp""
soap.wsdl_cache_ttl = 86400
soap.wsdl_cache_limit = 5

[ldap]
ldap.max_links = -1

[dba]

[opcache]
opcache.enable = 1
opcache.enable_cli = 1
opcache.memory_consumption = 128
opcache.interned_strings_buffer = 8
opcache.max_accelerated_files = 10000
opcache.revalidate_freq = 2
opcache.fast_shutdown = 1

[curl]

[openssl]
";
        
        File.WriteAllText(Path.Combine(configPath, "php.ini"), content);
        _module.Log("Generated config/php.ini");
    }
}
